@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}


###

# @name sendMail
POST {{baseUrl}}/email/send
Content-Type: application/json

{
  "email": "hiagohps360@gmail.com",
  "password": "123"
}

