@baseUrl = http://localhost:3335

###

# @name sendMail
POST {{baseUrl}}/email/send
Content-Type: application/json

{ 
  "to": "hiagohps360@gmail.com",
  "subject": "Test", 
  "text": "Teste de envio de email"
}

